apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crawlapp.fullname" . }}
  labels:
    {{- include "crawlapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "crawlapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crawlapp.selectorLabels" . | nindent 8 }}
    spec:
      # work on adding range lookup for containers array here tomorrow 5/22/2021
      {{- if .Values.containers }}
      containers:
        {{- range .Values.containers }}
        - name: {{ .name }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          ports:
          - containerPort: 8080
          volumeMounts:
            {{- range $.Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
        {{- end }}
      {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}
