apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: crawl
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "azurefile"
  resources:
    requests:
      storage: 5Gi