apiVersion: v1
kind: Service
metadata:
  name: crawl-git-service
spec:
  selector:
    app: crawl-git
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawl-git
  labels:
    app: crawl-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawl-git
  template:
    metadata:
      labels:
        app: crawl-git
    spec:
      containers:
      - name: crawl
        image: saitcho/crawl:latest
        ports:
        - containerPort: 8080
        volumeMounts: 
          - name: azure
            mountPath: /data
          - name: azuredisk
            mountPath: /websockets
      volumes:
      - name: azure
        persistentVolumeClaim:
          claimName: azurefile
      - name: azuredisk
        persistentVolumeClaim:
          claimName: azure-managed-disk